#!/bin/sh

generate_list() {
    count=0
    for entry in $( find ./entries -type f ); do
        count=$(( count + 1 ))
        . ${entry}
        entry_name="$( basename ${entry} )"
        [ ${count} -eq 1 ] && first_entry="${entry_name}" && prev_entry="${entry_name}"
        mkdir -p "public/${entry_name}"
        printf "<html><meta http-equiv=\"Refresh\" content=\"0; url='%s'\" /></html>\n" "${url}" \
            > "public/${entry_name}/index.html"
        cp "public/${entry_name}/index.html" "public/${prev_entry}/next.html"
        cp "public/${prev_entry}/index.html" "public/${entry_name}/previous.html"
        prev_entry="${entry_name}"
        [ -n "${author}" ] \
            && printf '<li><a href="%s">%s</a> by %s</li>\n' "${url}" "${title}" "${author}" \
            || printf '<li><a href="%s">%s</a></li>\n' "${url}" "${title}"
        unset url title author
    done
    cp "public/${first_entry}/index.html" "public/${entry_name}/next.html"
    cp "public/${entry_name}/index.html" "public/${first_entry}/previous.html"
}

cat << INDEX_PAGE > public/index.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="text/html; charset=UTF-8" http-equiv="content-type">
    <meta content="width=device-width,initial-scale=1" name="viewport">
    <title>webring</title>
    <meta content="webring" name="title">
    <meta content="Ahmed M Alaa" name="author">
    <meta content="Minimal webring" name="description">
    <meta content="website" property="og:type">
    <meta content="https://wr.4b.cx/" property="og:url">
    <meta content="webring" property="og:site_name">
    <meta content="webring" property="og:title">
    <meta content="Minimal webring" property="og:description">
    <meta content="summary" property="twitter:card">
    <meta content="https://wr.4b.cx/" property="twitter:url">
    <meta content="webring" property="twitter:title">
    <meta content="Minimal webring" property="twitter:description">
    <link href="https://wr.4b.cx/" rel="canonical">
    <link href="data:," rel="icon">
    <script type="application/ld+json">
        {
                "description":"Minimal webring",
                "url":"https://wr.4b.cx/",
                "@type":"WebSite",
                "headline":"webring",
                "name":"webring",
                "author":{
                    "@type":"Person",
                    "name":"Ahmed M Alaa"
                },
                "@context":"https://schema.org"
            }
    </script>
    <style>
        html { height:100%; background:white; }
        body { background:white; color:black; font-family:monospace; font-size:16px; line-height:1.4; margin:0; padding:4rem 0; min-height:100%; overflow-wrap:break-word; }
        main { max-width:640px; margin:0 auto; padding:0 2rem; }
        h1 { text-align:center }
        ul { display: flow-root; }
        li, nav a { width: 40%; float: left; margin: 0 5%; }
        nav a { display: block; text-align: center; }
        body[theme="dark"] { filter:invert(1); }
        @media (prefers-color-scheme: dark) { body[theme="auto"] { filter:invert(1); } }
        @media (max-width:640px) { li { width: 90%;  } }
    </style>
</head>

<body theme="auto">
    <main>
        <h1>webring</h1>
        <hr />
        <ul>
            $( generate_list )
        </ul>
        <hr />
        <p>This is an attempt to replicate <a href="https://wiki.xxiivv.com/site/devine_lu_linvega.html">Devine Lu Linvega</a>'s <a href="https://webring.xxiivv.com/">webring</a> in a very minimal way, and with a lower technical bar.</p>
        <p>To add your site to the webring, follow the instructions <a href="https://github.com/4bcx/webring#add-your-website-to-this-webring">here</a>. For issues, source code, documentation, visit the <a href="https://github.com/4bcx/webring">project page on GitHub</a></p>
        <p>This project is licensed under <a href="https://raw.githubusercontent.com/4bcx/webring/main/LICENSE">MIT license</a></p>
        <hr />
        <nav>
            <a href="https://wr.4b.cx/wr.4b.cx/previous">&larr; previous</a>
            <a href="https://wr.4b.cx/wr.4b.cx/next">next &rarr;</a>
        </nav>
    </main>
</body>

</html>
INDEX_PAGE